include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
    avoid_dynamic_calls: false
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false