name: record
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #  Main packages
  dio: ^4.0.0
  intl: ^0.17.0
  flutter_bloc: ^7.0.1
  hydrated_bloc: ^7.0.1

  #  Functionality packages
  just_audio: ^0.9.2

  #  UI packages
  cached_network_image: ^3.1.0
  cupertino_icons: ^1.0.3
  flutter_card_swipper: ^0.4.0
  get_it: ^7.2.0
  flutter_svg: ^0.22.0

  #  Generator packages
  freezed: ^0.14.2
  json_serializable: ^4.1.3


dev_dependencies:
  build_runner: ^2.0.6
  very_good_analysis: ^2.1.2
  flutter_gen_runner: ^3.1.1

#  flutter_launcher_icons: ^0.9.0
#  flutter_native_splash: ^1.2.0

flutter_gen:
  integrations:
    flutter_svg: true

  colors:
    inputs:
      - assets/colors/colors.xml

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logos/
    - assets/images/_app_icon/
    - assets/images/_splash_screen/